-- =====================================================================
--  Formula 1 statisztikai webalkalmazás
--  TELJES ADATBÁZIS-SÉMA – PostgreSQL 15+ / Supabase
--
--  Ez az egyetlen fájl, amit futtatnod kell. Tartalmazza:
--    - a teljes alapsémát (korábban 02_schema_postgres_supabase.sql)
--    - az OpenF1-integráció kiegészítéseit (korábban 03_openf1_migracio.sql)
--
--  *** IDEMPOTENS ***
--  Tetszőleges számú alkalommal újrafuttatható. Nem dob el táblát, nem
--  töröl adatot, és nem hibázik el akkor sem, ha egy objektum már létezik.
--  Meglévő adatbázison "felzárkóztató" migrációként működik: a hiányzó
--  oszlopokat, megszorításokat, indexeket, triggereket és policy-ket
--  létrehozza, a meglévőket frissíti.
--
--  Futtatás:
--    Supabase Dashboard -> SQL Editor -> beilleszt -> Run
--    vagy:  psql "$DATABASE_URL" -f 00_teljes_sema.sql
--
--  Az egész EGYETLEN TRANZAKCIÓBAN fut: ha bármi elhasal, semmi nem
--  marad félkész állapotban.
--
--  A csak egyszer futtatandó lépéseket (kiterjesztések, pg_cron ütemezés,
--  admin kinevezése, első szinkron) lásd: 01_egyszeri_parancsok.sql
--
--  TARTALOM
--    0.  Segédfüggvények az idempotenciához
--    1.  Törzsadat-táblák       (circuits, constructors, drivers, grandprix)
--    2.  Tranzakciós táblák     (race_result, qualifying_result, teams_drivers)
--    3.  OpenF1 azonosítók a meglévő táblákon
--    4.  OpenF1 táblák          (laps, pit_stops, stints, weather)
--    5.  Szinkron-napló         (sync_log)
--    6.  Jogosultság            (profiles + is_admin)
--    7.  Triggerfüggvények
--    8.  Triggerek bekötése
--    9.  Nézetek (bajnoki tabellák)
--    10. Nézet (gumistratégia)
--    11. RPC függvények
--    12. Row Level Security
--    13. RLS az OpenF1-táblákon
--    14. Jogosultságok (GRANT)
--    15. Identity szekvenciák szinkronizálása
--    16. Sémaverzió
-- =====================================================================

BEGIN;

SET LOCAL client_min_messages = WARNING;


-- =====================================================================
--  0. SEGÉDFÜGGVÉNYEK AZ IDEMPOTENCIÁHOZ
-- =====================================================================

-- A PostgreSQL-ben nincs `ALTER TABLE ... ADD CONSTRAINT IF NOT EXISTS`,
-- ezért egy segédfüggvény ellenőrzi, hogy létezik-e már a megszorítás.
CREATE OR REPLACE FUNCTION app_add_constraint(
    p_table      TEXT,
    p_constraint TEXT,
    p_definition TEXT
) RETURNS VOID
LANGUAGE plpgsql AS $fn$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM   pg_constraint c
        JOIN   pg_class      t ON t.oid = c.conrelid
        JOIN   pg_namespace  n ON n.oid = t.relnamespace
        WHERE  n.nspname = 'public'
          AND  t.relname = p_table
          AND  c.conname = p_constraint
    ) THEN
        EXECUTE format('ALTER TABLE public.%I ADD CONSTRAINT %I %s',
                       p_table, p_constraint, p_definition);
    END IF;
END;
$fn$;

-- Megszorítás biztonságos eltávolítása (séma-evolúcióhoz).
CREATE OR REPLACE FUNCTION app_drop_constraint(
    p_table      TEXT,
    p_constraint TEXT
) RETURNS VOID
LANGUAGE plpgsql AS $fn$
BEGIN
    EXECUTE format('ALTER TABLE public.%I DROP CONSTRAINT IF EXISTS %I',
                   p_table, p_constraint);
END;
$fn$;

-- updated_at karbantartás.
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$fn$;


-- =====================================================================
--  1. TÖRZSADAT-TÁBLÁK
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1.1 circuits – versenypályák
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS circuits (
    "CircuitID"      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"           VARCHAR(150) NOT NULL,
    "Location"       VARCHAR(100),
    "Country"        VARCHAR(50),
    "Length"         NUMERIC(5,3),
    "Laps"           SMALLINT,
    "FirstGrandPrix" SMALLINT,
    "RecordDriver"   VARCHAR(100),
    "RecordLapTime"  INTERVAL,
    "Image"          VARCHAR(255) NOT NULL DEFAULT ''
);

-- Séma-evolúció: ezek az oszlopok egy régebbi verzióból hiányozhatnak.
ALTER TABLE circuits ADD COLUMN IF NOT EXISTS "Location"       VARCHAR(100);
ALTER TABLE circuits ADD COLUMN IF NOT EXISTS "Country"        VARCHAR(50);
ALTER TABLE circuits ADD COLUMN IF NOT EXISTS "Length"         NUMERIC(5,3);
ALTER TABLE circuits ADD COLUMN IF NOT EXISTS "Laps"           SMALLINT;
ALTER TABLE circuits ADD COLUMN IF NOT EXISTS "FirstGrandPrix" SMALLINT;
ALTER TABLE circuits ADD COLUMN IF NOT EXISTS "RecordDriver"   VARCHAR(100);
ALTER TABLE circuits ADD COLUMN IF NOT EXISTS "RecordLapTime"  INTERVAL;
ALTER TABLE circuits ADD COLUMN IF NOT EXISTS "Image"          VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE circuits ADD COLUMN IF NOT EXISTS created_at       TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE circuits ADD COLUMN IF NOT EXISTS updated_at       TIMESTAMPTZ NOT NULL DEFAULT now();

-- Képattribúció (saját / szabad licencű grafikákhoz – kephasznalat_es_jogok.md)
ALTER TABLE circuits ADD COLUMN IF NOT EXISTS image_author     VARCHAR(255);
ALTER TABLE circuits ADD COLUMN IF NOT EXISTS image_license    VARCHAR(64);
ALTER TABLE circuits ADD COLUMN IF NOT EXISTS image_source_url VARCHAR(500);

SELECT app_add_constraint('circuits', 'chk_circuit_length',
    'CHECK ("Length" IS NULL OR "Length" > 0)');
SELECT app_add_constraint('circuits', 'chk_laps_positive_circuits',
    'CHECK ("Laps" IS NULL OR "Laps" > 0)');
SELECT app_add_constraint('circuits', 'chk_circuit_name',
    'CHECK (length(btrim("Name")) > 0)');
SELECT app_add_constraint('circuits', 'chk_first_gp_year',
    'CHECK ("FirstGrandPrix" IS NULL OR "FirstGrandPrix" BETWEEN 1900 AND 2100)');

COMMENT ON COLUMN circuits."Length" IS 'Pálya hossza km-ben';
COMMENT ON COLUMN circuits."RecordLapTime" IS 'Köridő-rekord INTERVAL-ként: 00:01:31.447 = 1 perc 31,447 mp. A MySQL TIME oszlop az 01:31.447 formátumot hibásan 1 óra 31 percként értelmezte.';


-- ---------------------------------------------------------------------
-- 1.2 constructors – csapatok
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS constructors (
    "ConstructorID"      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"               VARCHAR(150) NOT NULL,
    "Nationality"        VARCHAR(50),
    "FoundedYear"        SMALLINT,
    "TeamPrincipal"      VARCHAR(100),
    "Wins"               INTEGER  NOT NULL DEFAULT 0,
    "PolePositions"      INTEGER  NOT NULL DEFAULT 0,
    "Podiums"            INTEGER  NOT NULL DEFAULT 0,
    "WorldChampionships" SMALLINT NOT NULL DEFAULT 0,
    "History"            TEXT,
    "Image"              VARCHAR(255) NOT NULL DEFAULT ''
);

ALTER TABLE constructors ADD COLUMN IF NOT EXISTS "Nationality"        VARCHAR(50);
ALTER TABLE constructors ADD COLUMN IF NOT EXISTS "FoundedYear"        SMALLINT;
ALTER TABLE constructors ADD COLUMN IF NOT EXISTS "TeamPrincipal"      VARCHAR(100);
ALTER TABLE constructors ADD COLUMN IF NOT EXISTS "Wins"               INTEGER  NOT NULL DEFAULT 0;
ALTER TABLE constructors ADD COLUMN IF NOT EXISTS "PolePositions"      INTEGER  NOT NULL DEFAULT 0;
ALTER TABLE constructors ADD COLUMN IF NOT EXISTS "Podiums"            INTEGER  NOT NULL DEFAULT 0;
ALTER TABLE constructors ADD COLUMN IF NOT EXISTS "WorldChampionships" SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE constructors ADD COLUMN IF NOT EXISTS "History"            TEXT;
ALTER TABLE constructors ADD COLUMN IF NOT EXISTS "Image"              VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE constructors ADD COLUMN IF NOT EXISTS "TeamColour"         VARCHAR(7);
ALTER TABLE constructors ADD COLUMN IF NOT EXISTS created_at           TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE constructors ADD COLUMN IF NOT EXISTS updated_at           TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE constructors ADD COLUMN IF NOT EXISTS image_author         VARCHAR(255);
ALTER TABLE constructors ADD COLUMN IF NOT EXISTS image_license        VARCHAR(64);
ALTER TABLE constructors ADD COLUMN IF NOT EXISTS image_source_url     VARCHAR(500);

SELECT app_add_constraint('constructors', 'constructors_name_unique', 'UNIQUE ("Name")');
SELECT app_add_constraint('constructors', 'chk_founded_year_min',
    'CHECK ("FoundedYear" IS NULL OR "FoundedYear" >= 1900)');
SELECT app_add_constraint('constructors', 'chk_name_not_empty_constructor',
    'CHECK (length(btrim("Name")) > 0)');
SELECT app_add_constraint('constructors', 'chk_wins_nonneg',    'CHECK ("Wins" >= 0)');
SELECT app_add_constraint('constructors', 'chk_poles_nonneg',   'CHECK ("PolePositions" >= 0)');
SELECT app_add_constraint('constructors', 'chk_podiums_nonneg', 'CHECK ("Podiums" >= 0)');
SELECT app_add_constraint('constructors', 'chk_wdc_nonneg',     'CHECK ("WorldChampionships" >= 0)');
SELECT app_add_constraint('constructors', 'chk_team_colour_hex',
    'CHECK ("TeamColour" IS NULL OR "TeamColour" ~ ''^#[0-9A-Fa-f]{6}$'')');

COMMENT ON COLUMN constructors."TeamColour" IS 'Csapatszín hex kódja (#RRGGBB). A frontend gradiensei ebből épülnek, így nem kell hardkódolt színtérkép a kódban.';


-- ---------------------------------------------------------------------
-- 1.3 drivers – versenyzők
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS drivers (
    "DriverID"      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"          VARCHAR(150) NOT NULL,
    "ConstructorID" BIGINT,
    "Nationality"   VARCHAR(50),
    "BirthDate"     DATE,
    "Biography"     TEXT,
    "Image"         VARCHAR(255) NOT NULL DEFAULT ''
);

ALTER TABLE drivers ADD COLUMN IF NOT EXISTS "ConstructorID"  BIGINT;
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS "Nationality"    VARCHAR(50);
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS "BirthDate"      DATE;
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS "Biography"      TEXT;
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS "Image"          VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS "DriverNumber"   SMALLINT;
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS "Acronym"        CHAR(3);
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS created_at       TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS updated_at       TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS image_author     VARCHAR(255);
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS image_license    VARCHAR(64);
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS image_source_url VARCHAR(500);

SELECT app_add_constraint('drivers', 'drivers_constructorid_fkey',
    'FOREIGN KEY ("ConstructorID") REFERENCES constructors("ConstructorID") ON DELETE SET NULL ON UPDATE CASCADE');
SELECT app_add_constraint('drivers', 'chk_driver_name_not_empty',
    'CHECK (length(btrim("Name")) > 0)');
SELECT app_add_constraint('drivers', 'chk_driver_number',
    'CHECK ("DriverNumber" IS NULL OR "DriverNumber" BETWEEN 1 AND 99)');

CREATE INDEX IF NOT EXISTS drivers_constructorid_idx ON drivers ("ConstructorID");

COMMENT ON COLUMN drivers."DriverNumber" IS 'Rajtszám. A generált SVG-avatar (DriverAvatar komponens) ebből épül, ha nincs saját kép.';
COMMENT ON COLUMN drivers."Acronym"      IS 'Háromjegyű rövidítés, pl. VER, NOR, LEC.';


-- ---------------------------------------------------------------------
-- 1.4 grandprix – nagydíjak
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS grandprix (
    "GrandPrixID"    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"           VARCHAR(150) NOT NULL,
    "Country"        VARCHAR(50),
    "CircuitID"      BIGINT,
    "Year"           SMALLINT NOT NULL,
    "WinnerDriverID" BIGINT,
    "Image"          VARCHAR(255) NOT NULL DEFAULT ''
);

ALTER TABLE grandprix ADD COLUMN IF NOT EXISTS "Country"        VARCHAR(50);
ALTER TABLE grandprix ADD COLUMN IF NOT EXISTS "CircuitID"      BIGINT;
ALTER TABLE grandprix ADD COLUMN IF NOT EXISTS "WinnerDriverID" BIGINT;
ALTER TABLE grandprix ADD COLUMN IF NOT EXISTS "Image"          VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE grandprix ADD COLUMN IF NOT EXISTS "Round"          SMALLINT;
ALTER TABLE grandprix ADD COLUMN IF NOT EXISTS "RaceDate"       DATE;
ALTER TABLE grandprix ADD COLUMN IF NOT EXISTS created_at       TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE grandprix ADD COLUMN IF NOT EXISTS updated_at       TIMESTAMPTZ NOT NULL DEFAULT now();

-- SÉMAJAVÍTÁS: eredetileg a "Name" GLOBÁLISAN egyedi volt, így 2025-ben nem
-- lehetett felvinni a "Hungarian Grand Prix"-t, mert 2024-ben már létezett.
-- A helyes kulcs: (Name, Year).
SELECT app_drop_constraint('grandprix', 'grandprix_Name_key');
SELECT app_drop_constraint('grandprix', 'grandprix_name_key');
SELECT app_add_constraint('grandprix', 'grandprix_name_year_unique',
    'UNIQUE ("Name", "Year")');

SELECT app_add_constraint('grandprix', 'grandprix_circuitid_fkey',
    'FOREIGN KEY ("CircuitID") REFERENCES circuits("CircuitID") ON DELETE SET NULL ON UPDATE CASCADE');
SELECT app_add_constraint('grandprix', 'grandprix_winnerdriverid_fkey',
    'FOREIGN KEY ("WinnerDriverID") REFERENCES drivers("DriverID") ON DELETE SET NULL ON UPDATE CASCADE');
SELECT app_add_constraint('grandprix', 'chk_year_range',
    'CHECK ("Year" BETWEEN 1950 AND 2100)');
SELECT app_add_constraint('grandprix', 'chk_name_not_empty_grandprix',
    'CHECK (length(btrim("Name")) > 0)');

CREATE INDEX IF NOT EXISTS grandprix_circuitid_idx      ON grandprix ("CircuitID");
CREATE INDEX IF NOT EXISTS grandprix_winnerdriverid_idx ON grandprix ("WinnerDriverID");
CREATE INDEX IF NOT EXISTS grandprix_year_idx           ON grandprix ("Year");


-- =====================================================================
--  2. TRANZAKCIÓS TÁBLÁK
-- =====================================================================

-- ---------------------------------------------------------------------
-- 2.1 race_result – futameredmények
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS race_result (
    "ResultID"      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GrandPrixID"   BIGINT NOT NULL,
    "DriverID"      BIGINT NOT NULL,
    "ConstructorID" BIGINT NOT NULL,
    "Position"      INTEGER,
    "Grid"          INTEGER,
    "Laps"          INTEGER,
    "TimeOrRetired" VARCHAR(50),
    "Points"        NUMERIC(4,1) NOT NULL DEFAULT 0,
    "FastestLap"    BOOLEAN      NOT NULL DEFAULT FALSE,
    "GpOrSprint"    BOOLEAN      NOT NULL DEFAULT TRUE
);

ALTER TABLE race_result ADD COLUMN IF NOT EXISTS "Position"      INTEGER;
ALTER TABLE race_result ADD COLUMN IF NOT EXISTS "Grid"          INTEGER;
ALTER TABLE race_result ADD COLUMN IF NOT EXISTS "Laps"          INTEGER;
ALTER TABLE race_result ADD COLUMN IF NOT EXISTS "TimeOrRetired" VARCHAR(50);
ALTER TABLE race_result ADD COLUMN IF NOT EXISTS "Points"        NUMERIC(4,1) NOT NULL DEFAULT 0;
ALTER TABLE race_result ADD COLUMN IF NOT EXISTS "FastestLap"    BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE race_result ADD COLUMN IF NOT EXISTS "GpOrSprint"    BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE race_result ADD COLUMN IF NOT EXISTS created_at      TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE race_result ADD COLUMN IF NOT EXISTS updated_at      TIMESTAMPTZ NOT NULL DEFAULT now();

SELECT app_add_constraint('race_result', 'race_result_grandprixid_fkey',
    'FOREIGN KEY ("GrandPrixID") REFERENCES grandprix("GrandPrixID") ON DELETE RESTRICT ON UPDATE CASCADE');
SELECT app_add_constraint('race_result', 'race_result_driverid_fkey',
    'FOREIGN KEY ("DriverID") REFERENCES drivers("DriverID") ON DELETE RESTRICT ON UPDATE CASCADE');
SELECT app_add_constraint('race_result', 'race_result_constructorid_fkey',
    'FOREIGN KEY ("ConstructorID") REFERENCES constructors("ConstructorID") ON DELETE RESTRICT ON UPDATE CASCADE');
SELECT app_add_constraint('race_result', 'race_result_gp_driver_type_unique',
    'UNIQUE ("GrandPrixID", "DriverID", "GpOrSprint")');
SELECT app_add_constraint('race_result', 'chk_position_range',
    'CHECK ("Position" IS NULL OR "Position" BETWEEN 1 AND 26)');
SELECT app_add_constraint('race_result', 'chk_points_range',
    'CHECK ("Points" BETWEEN 0 AND 26)');
SELECT app_add_constraint('race_result', 'chk_grid_positive',
    'CHECK ("Grid" IS NULL OR "Grid" > 0)');
SELECT app_add_constraint('race_result', 'chk_laps_positive_raceresult',
    'CHECK ("Laps" IS NULL OR "Laps" >= 0)');

CREATE INDEX IF NOT EXISTS race_result_driverid_idx      ON race_result ("DriverID");
CREATE INDEX IF NOT EXISTS race_result_constructorid_idx ON race_result ("ConstructorID");
CREATE INDEX IF NOT EXISTS race_result_grandprixid_idx   ON race_result ("GrandPrixID");

-- Pozíció-egyediség futamon belül. Részleges egyedi index: race condition-mentes
-- és indexelt, szemben a MySQL COUNT(*)-os triggerével.
CREATE UNIQUE INDEX IF NOT EXISTS race_result_unique_position
    ON race_result ("GrandPrixID", "GpOrSprint", "Position")
    WHERE "Position" IS NOT NULL;

COMMENT ON COLUMN race_result."Position"   IS 'Helyezés, NULL = nem fejezte be';
COMMENT ON COLUMN race_result."GpOrSprint" IS 'TRUE = Grand Prix, FALSE = sprint';
COMMENT ON COLUMN race_result."Points"     IS 'A trg_assign_points trigger számolja, kézzel ne írd';


-- ---------------------------------------------------------------------
-- 2.2 qualifying_result – időmérős eredmények
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS qualifying_result (
    "QualifyingID"  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GrandPrixID"   BIGINT NOT NULL,
    "DriverID"      BIGINT NOT NULL,
    "ConstructorID" BIGINT,
    "GridPosition"  INTEGER
);

ALTER TABLE qualifying_result ADD COLUMN IF NOT EXISTS "ConstructorID" BIGINT;
ALTER TABLE qualifying_result ADD COLUMN IF NOT EXISTS "GridPosition"  INTEGER;
ALTER TABLE qualifying_result ADD COLUMN IF NOT EXISTS "Q1Time"        INTERVAL;
ALTER TABLE qualifying_result ADD COLUMN IF NOT EXISTS "Q2Time"        INTERVAL;
ALTER TABLE qualifying_result ADD COLUMN IF NOT EXISTS "Q3Time"        INTERVAL;
ALTER TABLE qualifying_result ADD COLUMN IF NOT EXISTS created_at      TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE qualifying_result ADD COLUMN IF NOT EXISTS updated_at      TIMESTAMPTZ NOT NULL DEFAULT now();

SELECT app_add_constraint('qualifying_result', 'qualifying_result_grandprixid_fkey',
    'FOREIGN KEY ("GrandPrixID") REFERENCES grandprix("GrandPrixID") ON DELETE CASCADE ON UPDATE CASCADE');
SELECT app_add_constraint('qualifying_result', 'qualifying_result_driverid_fkey',
    'FOREIGN KEY ("DriverID") REFERENCES drivers("DriverID") ON DELETE CASCADE ON UPDATE CASCADE');
SELECT app_add_constraint('qualifying_result', 'qualifying_result_constructorid_fkey',
    'FOREIGN KEY ("ConstructorID") REFERENCES constructors("ConstructorID") ON DELETE SET NULL ON UPDATE CASCADE');
SELECT app_add_constraint('qualifying_result', 'chk_grid_position',
    'CHECK ("GridPosition" IS NULL OR "GridPosition" BETWEEN 1 AND 26)');
SELECT app_add_constraint('qualifying_result', 'chk_q2_requires_q1',
    'CHECK ("Q2Time" IS NULL OR "Q1Time" IS NOT NULL)');
SELECT app_add_constraint('qualifying_result', 'chk_q3_requires_q2',
    'CHECK ("Q3Time" IS NULL OR "Q2Time" IS NOT NULL)');
SELECT app_add_constraint('qualifying_result', 'qualifying_result_gp_driver_unique',
    'UNIQUE ("GrandPrixID", "DriverID")');

CREATE INDEX IF NOT EXISTS qualifying_result_grandprixid_idx   ON qualifying_result ("GrandPrixID");
CREATE INDEX IF NOT EXISTS qualifying_result_driverid_idx      ON qualifying_result ("DriverID");
CREATE INDEX IF NOT EXISTS qualifying_result_constructorid_idx ON qualifying_result ("ConstructorID");


-- ---------------------------------------------------------------------
-- 2.3 teams_drivers – versenyző-csapat történet (M:N)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS teams_drivers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ConstructorID" BIGINT   NOT NULL,
    "DriverID"      BIGINT   NOT NULL,
    "FirstYear"     SMALLINT NOT NULL,
    "EndYear"       SMALLINT
);

ALTER TABLE teams_drivers ADD COLUMN IF NOT EXISTS "EndYear"  SMALLINT;
ALTER TABLE teams_drivers ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE teams_drivers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

SELECT app_add_constraint('teams_drivers', 'teams_drivers_constructorid_fkey',
    'FOREIGN KEY ("ConstructorID") REFERENCES constructors("ConstructorID") ON DELETE RESTRICT ON UPDATE CASCADE');
SELECT app_add_constraint('teams_drivers', 'teams_drivers_driverid_fkey',
    'FOREIGN KEY ("DriverID") REFERENCES drivers("DriverID") ON DELETE RESTRICT ON UPDATE CASCADE');
SELECT app_add_constraint('teams_drivers', 'chk_year_order',
    'CHECK ("EndYear" IS NULL OR "EndYear" >= "FirstYear")');
SELECT app_add_constraint('teams_drivers', 'teams_drivers_unique_stint',
    'UNIQUE ("DriverID", "ConstructorID", "FirstYear")');

CREATE INDEX IF NOT EXISTS teams_drivers_constructorid_idx ON teams_drivers ("ConstructorID");
CREATE INDEX IF NOT EXISTS teams_drivers_driver_years_idx
    ON teams_drivers ("DriverID", "FirstYear", "EndYear");


-- =====================================================================
--  3. OPENF1 AZONOSÍTÓK A MEGLÉVŐ TÁBLÁKON
--
--  Ezek nélkül minden szinkron duplikálná a sorokat. Velük az
--  INSERT ... ON CONFLICT DO UPDATE ismételhetővé válik.
-- =====================================================================

ALTER TABLE grandprix    ADD COLUMN IF NOT EXISTS openf1_meeting_key INTEGER;
ALTER TABLE grandprix    ADD COLUMN IF NOT EXISTS openf1_session_key INTEGER;
ALTER TABLE grandprix    ADD COLUMN IF NOT EXISTS openf1_sprint_key  INTEGER;
ALTER TABLE grandprix    ADD COLUMN IF NOT EXISTS openf1_quali_key   INTEGER;

ALTER TABLE drivers      ADD COLUMN IF NOT EXISTS openf1_driver_number SMALLINT;
ALTER TABLE constructors ADD COLUMN IF NOT EXISTS openf1_team_name     VARCHAR(100);
ALTER TABLE circuits     ADD COLUMN IF NOT EXISTS openf1_circuit_key   INTEGER;

-- Egyedi kulcsok az UPSERT-hez. Részleges index: a kézzel felvitt,
-- OpenF1-azonosító nélküli sorokat nem zavarja.
CREATE UNIQUE INDEX IF NOT EXISTS grandprix_openf1_meeting_uniq
    ON grandprix (openf1_meeting_key) WHERE openf1_meeting_key IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS drivers_openf1_number_uniq
    ON drivers (openf1_driver_number) WHERE openf1_driver_number IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS constructors_openf1_team_uniq
    ON constructors (openf1_team_name) WHERE openf1_team_name IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS circuits_openf1_key_uniq
    ON circuits (openf1_circuit_key) WHERE openf1_circuit_key IS NOT NULL;

COMMENT ON COLUMN grandprix.openf1_session_key IS
    'A futam (Race) session_key-je. A sprint és az időmérő külön kulcsot kap.';
COMMENT ON COLUMN drivers.openf1_driver_number IS
    'A rajtszám az OpenF1 elsődleges versenyző-azonosítója. Vigyázat: a szám évek között gazdát cserélhet.';


-- =====================================================================
--  4. OPENF1 TÁBLÁK – köridők, boxkiállások, stintek, időjárás
--
--  Amit SZÁNDÉKOSAN NEM tárolunk: car_data (telemetria, ~3,7 Hz) és
--  location (GPS). Ezek ~40 MB/session méretűek – egyetlen hétvége
--  szétfeszítené a Supabase free tier 500 MB-ját. Ha kell, a
--  böngészőből hívd közvetlenül az OpenF1-et.
-- =====================================================================



CREATE TABLE IF NOT EXISTS laps (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GrandPrixID"     BIGINT   NOT NULL,
    "DriverID"        BIGINT   NOT NULL,
    session_key       INTEGER  NOT NULL,
    lap_number        SMALLINT NOT NULL,
    lap_duration      NUMERIC(8,3),
    duration_sector_1 NUMERIC(8,3),
    duration_sector_2 NUMERIC(8,3),
    duration_sector_3 NUMERIC(8,3),
    st_speed          SMALLINT,
    i1_speed          SMALLINT,
    i2_speed          SMALLINT,
    is_pit_out_lap    BOOLEAN NOT NULL DEFAULT FALSE,
    date_start        TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

SELECT app_add_constraint('laps', 'laps_grandprixid_fkey',
    'FOREIGN KEY ("GrandPrixID") REFERENCES grandprix("GrandPrixID") ON DELETE CASCADE');
SELECT app_add_constraint('laps', 'laps_driverid_fkey',
    'FOREIGN KEY ("DriverID") REFERENCES drivers("DriverID") ON DELETE CASCADE');
SELECT app_add_constraint('laps', 'laps_session_driver_lap_uniq',
    'UNIQUE (session_key, "DriverID", lap_number)');
SELECT app_add_constraint('laps', 'chk_lap_duration',
    'CHECK (lap_duration IS NULL OR lap_duration > 0)');

CREATE INDEX IF NOT EXISTS laps_gp_driver_idx ON laps ("GrandPrixID", "DriverID");
CREATE INDEX IF NOT EXISTS laps_duration_idx  ON laps (lap_duration) WHERE lap_duration IS NOT NULL;



CREATE TABLE IF NOT EXISTS pit_stops (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GrandPrixID" BIGINT   NOT NULL,
    "DriverID"    BIGINT   NOT NULL,
    session_key   INTEGER  NOT NULL,
    lap_number    SMALLINT NOT NULL,
    pit_duration  NUMERIC(6,2),
    date          TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

SELECT app_add_constraint('pit_stops', 'pit_stops_grandprixid_fkey',
    'FOREIGN KEY ("GrandPrixID") REFERENCES grandprix("GrandPrixID") ON DELETE CASCADE');
SELECT app_add_constraint('pit_stops', 'pit_stops_driverid_fkey',
    'FOREIGN KEY ("DriverID") REFERENCES drivers("DriverID") ON DELETE CASCADE');
SELECT app_add_constraint('pit_stops', 'pit_stops_uniq',
    'UNIQUE (session_key, "DriverID", lap_number)');

CREATE INDEX IF NOT EXISTS pit_stops_gp_idx ON pit_stops ("GrandPrixID");



CREATE TABLE IF NOT EXISTS stints (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GrandPrixID"     BIGINT   NOT NULL,
    "DriverID"        BIGINT   NOT NULL,
    session_key       INTEGER  NOT NULL,
    stint_number      SMALLINT NOT NULL,
    compound          VARCHAR(20),
    lap_start         SMALLINT,
    lap_end           SMALLINT,
    tyre_age_at_start SMALLINT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

SELECT app_add_constraint('stints', 'stints_grandprixid_fkey',
    'FOREIGN KEY ("GrandPrixID") REFERENCES grandprix("GrandPrixID") ON DELETE CASCADE');
SELECT app_add_constraint('stints', 'stints_driverid_fkey',
    'FOREIGN KEY ("DriverID") REFERENCES drivers("DriverID") ON DELETE CASCADE');
SELECT app_add_constraint('stints', 'stints_uniq',
    'UNIQUE (session_key, "DriverID", stint_number)');
SELECT app_add_constraint('stints', 'chk_compound',
    'CHECK (compound IS NULL OR compound IN (''SOFT'',''MEDIUM'',''HARD'',''INTERMEDIATE'',''WET'',''UNKNOWN''))');

CREATE INDEX IF NOT EXISTS stints_gp_idx ON stints ("GrandPrixID");



CREATE TABLE IF NOT EXISTS weather (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GrandPrixID"    BIGINT      NOT NULL,
    session_key      INTEGER     NOT NULL,
    date             TIMESTAMPTZ NOT NULL,
    air_temperature  NUMERIC(4,1),
    track_temperature NUMERIC(4,1),
    humidity         NUMERIC(4,1),
    pressure         NUMERIC(6,1),
    wind_speed       NUMERIC(4,1),
    wind_direction   SMALLINT,
    rainfall         SMALLINT
);

SELECT app_add_constraint('weather', 'weather_grandprixid_fkey',
    'FOREIGN KEY ("GrandPrixID") REFERENCES grandprix("GrandPrixID") ON DELETE CASCADE');
SELECT app_add_constraint('weather', 'weather_uniq',
    'UNIQUE (session_key, date)');

CREATE INDEX IF NOT EXISTS weather_gp_idx ON weather ("GrandPrixID");


-- =====================================================================
--  5. SZINKRON-NAPLÓ
--
--  Enélkül nincs mód megállapítani, mikor futott le mi, és mi hibázott.
-- =====================================================================

CREATE TABLE IF NOT EXISTS sync_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider     VARCHAR(30)  NOT NULL DEFAULT 'openf1',
    task         VARCHAR(50)  NOT NULL,
    season       SMALLINT,
    session_key  INTEGER,
    status       VARCHAR(20)  NOT NULL,
    rows_upserted INTEGER     NOT NULL DEFAULT 0,
    requests_made INTEGER     NOT NULL DEFAULT 0,
    message      TEXT,
    started_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    finished_at  TIMESTAMPTZ
);

SELECT app_add_constraint('sync_log', 'chk_sync_status',
    'CHECK (status IN (''running'',''ok'',''partial'',''error'',''skipped''))');

CREATE INDEX IF NOT EXISTS sync_log_started_idx ON sync_log (started_at DESC);
CREATE INDEX IF NOT EXISTS sync_log_task_idx    ON sync_log (task, started_at DESC);

/** Mikor futott utoljára sikeresen egy adott feladat? Inkrementális szinkronhoz. */
CREATE OR REPLACE FUNCTION last_successful_sync(p_task TEXT)
RETURNS TIMESTAMPTZ
LANGUAGE sql STABLE AS $fn$
    SELECT MAX(finished_at) FROM sync_log
    WHERE task = p_task AND status IN ('ok', 'partial');
$fn$;


-- =====================================================================
--  6. JOGOSULTSÁG – profiles tábla a Supabase Auth mellé
--
--  A Sanctum + users.Role helyett Supabase Auth. Az auth.users táblához
--  nem lehet közvetlenül oszlopot adni, ezért minden felhasználóhoz egy
--  public.profiles sor tartozik.
-- =====================================================================

CREATE TABLE IF NOT EXISTS profiles (
    id         UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email      TEXT,
    role       TEXT NOT NULL DEFAULT 'user',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE profiles ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS role  TEXT NOT NULL DEFAULT 'user';

SELECT app_add_constraint('profiles', 'chk_profile_role',
    'CHECK (role IN (''user'', ''admin''))');

-- Regisztrációnál automatikusan létrejön a profil, mindig 'user' szereppel.
-- Adminná előléptetni csak SQL-ből vagy service_role kulccsal lehet.
CREATE OR REPLACE FUNCTION handle_new_user() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $fn$
BEGIN
    INSERT INTO public.profiles (id, email)
    VALUES (NEW.id, NEW.email)
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$fn$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- Admin-ellenőrzés. SECURITY DEFINER, hogy az RLS-policy-kből hívva a
-- profiles saját policy-je ne vigye végtelen rekurzióba a kiértékelést.
CREATE OR REPLACE FUNCTION is_admin() RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $fn$
    SELECT EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role = 'admin'
    );
$fn$;


-- =====================================================================
--  7. TRIGGERFÜGGVÉNYEK
-- =====================================================================

-- 4.1 Versenyző életkora legalább 18 év
CREATE OR REPLACE FUNCTION trg_check_driver_age() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
    IF NEW."BirthDate" IS NOT NULL
       AND age(CURRENT_DATE, NEW."BirthDate") < INTERVAL '18 years' THEN
        RAISE EXCEPTION 'A pilótának legalább 18 évesnek kell lennie (%)', NEW."Name"
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$fn$;

-- 4.2 Csapat alapítási éve nem lehet a jövőben
CREATE OR REPLACE FUNCTION trg_check_founded_year() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
    IF NEW."FoundedYear" > EXTRACT(YEAR FROM CURRENT_DATE) THEN
        RAISE EXCEPTION 'Az alapítás éve nem lehet a jövőben (%)', NEW."FoundedYear"
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$fn$;

-- 4.3 Mezőnyméret: 2024-től max. 20, korábban max. 26 pozíció
CREATE OR REPLACE FUNCTION trg_race_result_validate() RETURNS trigger
LANGUAGE plpgsql AS $fn$
DECLARE
    v_year  SMALLINT;
    v_count INTEGER;
    v_max   INTEGER;
BEGIN
    IF NEW."Position" IS NULL THEN
        RETURN NEW;
    END IF;

    SELECT "Year" INTO v_year FROM grandprix
    WHERE "GrandPrixID" = NEW."GrandPrixID";

    v_max := CASE WHEN v_year >= 2024 THEN 20 ELSE 26 END;

    SELECT COUNT(*) INTO v_count
    FROM   race_result
    WHERE  "GrandPrixID" = NEW."GrandPrixID"
      AND  "GpOrSprint"  = NEW."GpOrSprint"
      AND  "Position" IS NOT NULL
      AND  "ResultID" IS DISTINCT FROM NEW."ResultID";

    IF v_count >= v_max THEN
        RAISE EXCEPTION '% évi futamon legfeljebb % pozíció rögzíthető', v_year, v_max
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NEW;
END;
$fn$;

-- 4.4 Automatikus pontkiosztás
--
--  A MySQL sémában KÉT versengő BEFORE INSERT trigger írta a Points mezőt,
--  a második felülírta az elsőt. Itt egyetlen, teljes lefedettségű függvény,
--  és INSERT-re és UPDATE-re egyaránt fut.
CREATE OR REPLACE FUNCTION trg_assign_points() RETURNS trigger
LANGUAGE plpgsql AS $fn$
DECLARE
    v_year   SMALLINT;
    v_points NUMERIC(4,1) := 0;
BEGIN
    IF NEW."Position" IS NULL THEN
        NEW."Points" := 0;
        RETURN NEW;
    END IF;

    SELECT "Year" INTO v_year FROM grandprix
    WHERE "GrandPrixID" = NEW."GrandPrixID";

    IF NEW."GpOrSprint" = FALSE THEN
        -- Sprint (2021-től): 8-7-6-5-4-3-2-1
        v_points := CASE NEW."Position"
            WHEN 1 THEN 8 WHEN 2 THEN 7 WHEN 3 THEN 6 WHEN 4 THEN 5
            WHEN 5 THEN 4 WHEN 6 THEN 3 WHEN 7 THEN 2 WHEN 8 THEN 1
            ELSE 0 END;

    ELSIF v_year >= 2010 THEN
        v_points := CASE NEW."Position"
            WHEN 1 THEN 25 WHEN 2  THEN 18 WHEN 3 THEN 15 WHEN 4 THEN 12
            WHEN 5 THEN 10 WHEN 6  THEN  8 WHEN 7 THEN  6 WHEN 8 THEN  4
            WHEN 9 THEN  2 WHEN 10 THEN  1
            ELSE 0 END;

    ELSIF v_year BETWEEN 2003 AND 2009 THEN
        v_points := CASE NEW."Position"
            WHEN 1 THEN 10 WHEN 2 THEN 8 WHEN 3 THEN 6 WHEN 4 THEN 5
            WHEN 5 THEN  4 WHEN 6 THEN 3 WHEN 7 THEN 2 WHEN 8 THEN 1
            ELSE 0 END;

    ELSIF v_year BETWEEN 1991 AND 2002 THEN
        v_points := CASE NEW."Position"
            WHEN 1 THEN 10 WHEN 2 THEN 6 WHEN 3 THEN 4
            WHEN 4 THEN  3 WHEN 5 THEN 2 WHEN 6 THEN 1
            ELSE 0 END;
    END IF;

    -- Leggyorsabb körért járó +1 pont (2019-2024, futamon, top10).
    -- Az eredeti sémában ez elveszett: a seeder 26-ot írt, a trigger 25-re
    -- csökkentette. A chk_points_range felső határa (26) pont ezt engedi meg.
    IF NEW."FastestLap"
       AND NEW."GpOrSprint"
       AND v_year BETWEEN 2019 AND 2024
       AND NEW."Position" <= 10 THEN
        v_points := v_points + 1;
    END IF;

    NEW."Points" := v_points;
    RETURN NEW;
END;
$fn$;

-- 4.5 Futamgyőztes szinkronizálása
CREATE OR REPLACE FUNCTION trg_sync_race_winner() RETURNS trigger
LANGUAGE plpgsql AS $fn$
DECLARE
    v_gp     BIGINT := COALESCE(NEW."GrandPrixID", OLD."GrandPrixID");
    v_winner BIGINT;
BEGIN
    SELECT "DriverID" INTO v_winner
    FROM   race_result
    WHERE  "GrandPrixID" = v_gp
      AND  "GpOrSprint"  = TRUE
      AND  "Position"    = 1
    LIMIT  1;

    UPDATE grandprix
    SET    "WinnerDriverID" = v_winner
    WHERE  "GrandPrixID" = v_gp
      AND  "WinnerDriverID" IS DISTINCT FROM v_winner;

    RETURN NULL;
END;
$fn$;

-- 4.6 Futamgyőztes kézi módosításának tiltása
--
--  Két kivétel:
--   - pg_trigger_depth() > 1  -> a 4.5-ös trigger írja, ez legitim
--   - app.allow_winner_override = 'on' -> szándékos admin felülbírálás:
--       SET LOCAL app.allow_winner_override = 'on';
CREATE OR REPLACE FUNCTION trg_lock_race_winner() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
    IF pg_trigger_depth() > 1 THEN
        RETURN NEW;
    END IF;

    IF COALESCE(current_setting('app.allow_winner_override', TRUE), 'off') = 'on' THEN
        RETURN NEW;
    END IF;

    IF OLD."WinnerDriverID" IS NOT NULL
       AND NEW."WinnerDriverID" IS NOT NULL
       AND NEW."WinnerDriverID" <> OLD."WinnerDriverID" THEN
        RAISE EXCEPTION 'Egy verseny győztese nem módosítható közvetlenül. Írd át a futameredményt, vagy: SET LOCAL app.allow_winner_override = ''on'';'
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NEW;
END;
$fn$;


-- =====================================================================
--  8. TRIGGEREK BEKÖTÉSE
--
--  PostgreSQL a triggereket NÉV szerint ábécésorrendben futtatja (a MySQL
--  a létrehozás sorrendjében), ezért a nevek 'a_' / 'b_' / 'z_' előtaggal
--  kényszerítik ki a sorrendet. DROP + CREATE az újrafuttathatóság miatt.
-- =====================================================================

DROP TRIGGER IF EXISTS a_check_driver_age ON drivers;
CREATE TRIGGER a_check_driver_age
    BEFORE INSERT OR UPDATE ON drivers
    FOR EACH ROW EXECUTE FUNCTION trg_check_driver_age();

DROP TRIGGER IF EXISTS z_set_updated_at ON drivers;
CREATE TRIGGER z_set_updated_at
    BEFORE UPDATE ON drivers
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS a_check_founded_year ON constructors;
CREATE TRIGGER a_check_founded_year
    BEFORE INSERT OR UPDATE ON constructors
    FOR EACH ROW EXECUTE FUNCTION trg_check_founded_year();

DROP TRIGGER IF EXISTS z_set_updated_at ON constructors;
CREATE TRIGGER z_set_updated_at
    BEFORE UPDATE ON constructors
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS z_set_updated_at ON circuits;
CREATE TRIGGER z_set_updated_at
    BEFORE UPDATE ON circuits
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS a_lock_race_winner ON grandprix;
CREATE TRIGGER a_lock_race_winner
    BEFORE UPDATE ON grandprix
    FOR EACH ROW EXECUTE FUNCTION trg_lock_race_winner();

DROP TRIGGER IF EXISTS z_set_updated_at ON grandprix;
CREATE TRIGGER z_set_updated_at
    BEFORE UPDATE ON grandprix
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS a_race_result_validate ON race_result;
CREATE TRIGGER a_race_result_validate
    BEFORE INSERT OR UPDATE ON race_result
    FOR EACH ROW EXECUTE FUNCTION trg_race_result_validate();

DROP TRIGGER IF EXISTS b_assign_points ON race_result;
CREATE TRIGGER b_assign_points
    BEFORE INSERT OR UPDATE ON race_result
    FOR EACH ROW EXECUTE FUNCTION trg_assign_points();

DROP TRIGGER IF EXISTS z_set_updated_at ON race_result;
CREATE TRIGGER z_set_updated_at
    BEFORE UPDATE ON race_result
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS z_sync_race_winner ON race_result;
CREATE TRIGGER z_sync_race_winner
    AFTER INSERT OR UPDATE OR DELETE ON race_result
    FOR EACH ROW EXECUTE FUNCTION trg_sync_race_winner();

DROP TRIGGER IF EXISTS z_set_updated_at ON qualifying_result;
CREATE TRIGGER z_set_updated_at
    BEFORE UPDATE ON qualifying_result
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS z_set_updated_at ON teams_drivers;
CREATE TRIGGER z_set_updated_at
    BEFORE UPDATE ON teams_drivers
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS z_set_updated_at ON profiles;
CREATE TRIGGER z_set_updated_at
    BEFORE UPDATE ON profiles
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- =====================================================================
--  9. NÉZETEK – a StatisticsController aggregációi adatbázis-oldalon
--
--  DROP + CREATE: a nézet nem tárol adatot, így veszteségmentes, és akkor
--  is működik, ha az oszloplista változott (a CREATE OR REPLACE hibázna).
-- =====================================================================

DROP VIEW IF EXISTS v_driver_standings      CASCADE;
DROP VIEW IF EXISTS v_constructor_standings CASCADE;
DROP VIEW IF EXISTS v_driver_race_points    CASCADE;

CREATE VIEW v_driver_standings AS
SELECT  d."DriverID",
        d."Name"       AS driver_name,
        d."Nationality",
        d."DriverNumber",
        d."Acronym",
        d."Image",
        d."ConstructorID",
        c."Name"       AS constructor_name,
        c."TeamColour" AS team_colour,
        COALESCE(SUM(r."Points"), 0)::NUMERIC                           AS points,
        COUNT(*) FILTER (WHERE r."Position" = 1  AND r."GpOrSprint")     AS wins,
        COUNT(*) FILTER (WHERE r."Position" <= 3 AND r."GpOrSprint")     AS podiums,
        COUNT(*) FILTER (WHERE r."FastestLap")                           AS fastest_laps,
        COUNT(*) FILTER (WHERE r."GpOrSprint")                           AS races,
        COUNT(*) FILTER (WHERE r."Position" IS NULL AND r."GpOrSprint")  AS dnfs
FROM        drivers      d
LEFT JOIN   race_result  r ON r."DriverID"      = d."DriverID"
LEFT JOIN   constructors c ON c."ConstructorID" = d."ConstructorID"
GROUP BY    d."DriverID", d."Name", d."Nationality", d."DriverNumber",
            d."Acronym", d."Image", d."ConstructorID", c."Name", c."TeamColour";

CREATE VIEW v_constructor_standings AS
SELECT  c."ConstructorID",
        c."Name"       AS constructor_name,
        c."Nationality",
        c."Image",
        c."TeamColour" AS team_colour,
        COALESCE(SUM(r."Points"), 0)::NUMERIC                            AS points,
        COUNT(*) FILTER (WHERE r."Position" = 1  AND r."GpOrSprint")      AS wins,
        COUNT(*) FILTER (WHERE r."Position" <= 3 AND r."GpOrSprint")      AS podiums,
        COUNT(*) FILTER (WHERE r."FastestLap")                            AS fastest_laps,
        COUNT(DISTINCT r."GrandPrixID") FILTER (WHERE r."GpOrSprint")     AS races
FROM        constructors c
LEFT JOIN   race_result  r ON r."ConstructorID" = c."ConstructorID"
GROUP BY    c."ConstructorID", c."Name", c."Nationality", c."Image", c."TeamColour";

-- Futamonkénti pontbontás a statisztika-oldal oszlopdiagramjához.
CREATE VIEW v_driver_race_points AS
SELECT  r."DriverID",
        g."GrandPrixID",
        g."Name"    AS grand_prix_name,
        g."Country",
        g."Year",
        g."Round",
        SUM(r."Points")::NUMERIC AS points
FROM        race_result r
JOIN        grandprix   g ON g."GrandPrixID" = r."GrandPrixID"
GROUP BY    r."DriverID", g."GrandPrixID", g."Name", g."Country", g."Year", g."Round";

COMMENT ON VIEW v_driver_standings IS
    'A FILTER (WHERE "GpOrSprint") záradék az, ami a Laravel backendből hiányzott: enélkül a sprintgyőzelmek is futamgyőzelemnek számítottak.';


-- =====================================================================
--  10. NÉZET – gumistratégia idővonalhoz
-- =====================================================================

DROP VIEW IF EXISTS v_race_strategy CASCADE;

CREATE VIEW v_race_strategy AS
SELECT  s."GrandPrixID",
        s."DriverID",
        d."Name"       AS driver_name,
        d."Acronym",
        c."TeamColour" AS team_colour,
        s.stint_number,
        s.compound,
        s.lap_start,
        s.lap_end,
        s.tyre_age_at_start,
        (s.lap_end - s.lap_start + 1) AS stint_length
FROM        stints       s
JOIN        drivers      d ON d."DriverID"      = s."DriverID"
LEFT JOIN   constructors c ON c."ConstructorID" = d."ConstructorID";


-- =====================================================================
--  11. RPC FÜGGVÉNYEK – amit a nézet nem tud lefedni.
--     A frontend a supabase.rpc('...') hívással éri el őket.
-- =====================================================================

CREATE OR REPLACE FUNCTION driver_stats(p_driver_id BIGINT)
RETURNS JSON
LANGUAGE sql STABLE AS $fn$
    SELECT json_build_object(
        'driver',       (SELECT row_to_json(s) FROM v_driver_standings s
                         WHERE s."DriverID" = p_driver_id),
        'points_chart', COALESCE((SELECT json_agg(p ORDER BY p."Year", p."Round", p."GrandPrixID")
                                  FROM v_driver_race_points p
                                  WHERE p."DriverID" = p_driver_id), '[]'::json)
    );
$fn$;

CREATE OR REPLACE FUNCTION constructor_stats(p_constructor_id BIGINT)
RETURNS JSON
LANGUAGE sql STABLE AS $fn$
    SELECT json_build_object(
        'constructor',  (SELECT row_to_json(s) FROM v_constructor_standings s
                         WHERE s."ConstructorID" = p_constructor_id),
        'drivers',      COALESCE((SELECT json_agg(d ORDER BY d.points DESC)
                                  FROM v_driver_standings d
                                  WHERE d."ConstructorID" = p_constructor_id), '[]'::json),
        'points_chart', COALESCE((SELECT json_agg(x ORDER BY x."Year", x."Round", x."GrandPrixID")
                                  FROM (
                                      SELECT g."GrandPrixID", g."Name" AS grand_prix_name,
                                             g."Country", g."Year", g."Round",
                                             SUM(r."Points")::NUMERIC AS points
                                      FROM   race_result r
                                      JOIN   grandprix   g ON g."GrandPrixID" = r."GrandPrixID"
                                      WHERE  r."ConstructorID" = p_constructor_id
                                      GROUP  BY g."GrandPrixID", g."Name", g."Country", g."Year", g."Round"
                                  ) x), '[]'::json)
    );
$fn$;


-- =====================================================================
--  12. ROW LEVEL SECURITY
--
--  A Supabase minden public táblát publikál a PostgREST Data API-n.
--  RLS nélkül az anon kulccsal bárki írhatna/törölhetne – pontosan az a
--  hiba, ami a Laravel routes/api.php-ban is megvolt.
--
--  Modell: mindenki OLVAS, csak az admin ír.
-- =====================================================================

ALTER TABLE circuits          ENABLE ROW LEVEL SECURITY;
ALTER TABLE constructors      ENABLE ROW LEVEL SECURITY;
ALTER TABLE drivers           ENABLE ROW LEVEL SECURITY;
ALTER TABLE grandprix         ENABLE ROW LEVEL SECURITY;
ALTER TABLE race_result       ENABLE ROW LEVEL SECURITY;
ALTER TABLE qualifying_result ENABLE ROW LEVEL SECURITY;
ALTER TABLE teams_drivers     ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles          ENABLE ROW LEVEL SECURITY;

DO $do$
DECLARE
    t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY['circuits','constructors','drivers','grandprix',
                             'race_result','qualifying_result','teams_drivers']
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS public_read ON public.%I', t);
        EXECUTE format('DROP POLICY IF EXISTS admin_write ON public.%I', t);

        EXECUTE format(
            'CREATE POLICY public_read ON public.%I
             FOR SELECT TO anon, authenticated USING (TRUE)', t);

        EXECUTE format(
            'CREATE POLICY admin_write ON public.%I
             FOR ALL TO authenticated
             USING (public.is_admin()) WITH CHECK (public.is_admin())', t);
    END LOOP;
END;
$do$;

-- profiles: mindenki a sajátját látja, az admin mindet
DROP POLICY IF EXISTS profiles_self_read ON profiles;
DROP POLICY IF EXISTS profiles_admin_all ON profiles;

CREATE POLICY profiles_self_read ON profiles
    FOR SELECT TO authenticated USING (id = auth.uid());

CREATE POLICY profiles_admin_all ON profiles
    FOR ALL TO authenticated
    USING (public.is_admin()) WITH CHECK (public.is_admin());


-- =====================================================================
--  13. RLS AZ OPENF1-TÁBLÁKON
--
--  Ugyanaz a modell: mindenki olvas, csak az admin ír.
--  A szinkron a service_role kulccsal fut, ami megkerüli az RLS-t.
-- =====================================================================

ALTER TABLE laps      ENABLE ROW LEVEL SECURITY;
ALTER TABLE pit_stops ENABLE ROW LEVEL SECURITY;
ALTER TABLE stints    ENABLE ROW LEVEL SECURITY;
ALTER TABLE weather   ENABLE ROW LEVEL SECURITY;
ALTER TABLE sync_log  ENABLE ROW LEVEL SECURITY;

DO $do$
DECLARE t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY['laps','pit_stops','stints','weather']
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS public_read ON public.%I', t);
        EXECUTE format('DROP POLICY IF EXISTS admin_write ON public.%I', t);
        EXECUTE format('CREATE POLICY public_read ON public.%I
                        FOR SELECT TO anon, authenticated USING (TRUE)', t);
        EXECUTE format('CREATE POLICY admin_write ON public.%I
                        FOR ALL TO authenticated
                        USING (public.is_admin()) WITH CHECK (public.is_admin())', t);
    END LOOP;
END;
$do$;

-- A szinkron-naplót csak admin láthatja: üzemeltetési adat.
DROP POLICY IF EXISTS sync_log_admin ON sync_log;
CREATE POLICY sync_log_admin ON sync_log
    FOR SELECT TO authenticated USING (public.is_admin());

GRANT SELECT ON laps, pit_stops, stints, weather, v_race_strategy
    TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON laps, pit_stops, stints, weather TO authenticated;
GRANT SELECT ON sync_log TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT EXECUTE ON FUNCTION last_successful_sync(TEXT) TO authenticated;


-- =====================================================================
--  14. JOGOSULTSÁGOK
--
--  A 2026-05-30 után létrehozott Supabase projekteknél a PostgREST
--  eléréshez explicit GRANT is kell (a korábbiaknál 2026-10-30-tól).
-- =====================================================================

GRANT USAGE ON SCHEMA public TO anon, authenticated;

GRANT SELECT ON
    circuits, constructors, drivers, grandprix,
    race_result, qualifying_result, teams_drivers,
    v_driver_standings, v_constructor_standings, v_driver_race_points
TO anon, authenticated;

-- A tényleges szűrést az admin_write RLS-policy végzi.
GRANT INSERT, UPDATE, DELETE ON
    circuits, constructors, drivers, grandprix,
    race_result, qualifying_result, teams_drivers
TO authenticated;

GRANT SELECT, UPDATE ON profiles TO authenticated;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

GRANT EXECUTE ON FUNCTION driver_stats(BIGINT)      TO anon, authenticated;
GRANT EXECUTE ON FUNCTION constructor_stats(BIGINT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION is_admin()                TO anon, authenticated;


-- =====================================================================
--  15. IDENTITY SZEKVENCIÁK SZINKRONIZÁLÁSA
--
--  Ez a leggyakoribb Postgres-anomália migráció után: ha az adatokat
--  explicit ID-kkal töltöd be (INSERT ... ("DriverID", ...) VALUES (1, ...)),
--  a szekvencia nem lép, és a következő automatikus beszúrás
--  "duplicate key value violates unique constraint" hibával elszáll.
--
--  Ez a blokk minden futáskor újraigazítja a szekvenciákat.
-- =====================================================================

DO $do$
DECLARE
    r   RECORD;
    seq TEXT;
    mx  BIGINT;
BEGIN
    FOR r IN
        SELECT * FROM (VALUES
            ('circuits',          'CircuitID'),
            ('constructors',      'ConstructorID'),
            ('drivers',           'DriverID'),
            ('grandprix',         'GrandPrixID'),
            ('race_result',       'ResultID'),
            ('qualifying_result', 'QualifyingID'),
            ('teams_drivers',     'id'),
            ('laps',              'id'),
            ('pit_stops',         'id'),
            ('stints',            'id'),
            ('weather',           'id'),
            ('sync_log',          'id')
        ) AS t(tbl, col)
    LOOP
        seq := pg_get_serial_sequence('public.' || r.tbl, r.col);
        IF seq IS NOT NULL THEN
            EXECUTE format('SELECT COALESCE(MAX(%I), 0) FROM public.%I', r.col, r.tbl)
              INTO mx;
            PERFORM setval(seq, GREATEST(mx, 1), mx > 0);
        END IF;
    END LOOP;
END;
$do$;


-- =====================================================================
--  16. SÉMAVERZIÓ
-- =====================================================================

CREATE TABLE IF NOT EXISTS schema_version (
    version    TEXT PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    note       TEXT
);

INSERT INTO schema_version (version, note) VALUES
    ('2026.08.25-supabase',
     'Alapsema: multi-season UNIQUE(Name,Year), egyesitett pontszamito trigger, leggyorsabb kor +1 pont, RLS + profiles, nezetek es RPC-k.'),
    ('2026.08.25-openf1',
     'OpenF1 azonositok, laps/pit_stops/stints/weather tablak, sync_log, v_race_strategy nezet.')
ON CONFLICT (version) DO UPDATE SET applied_at = now();


COMMIT;


-- =====================================================================
--  ELLENŐRZÉS – futtasd le a séma után
-- =====================================================================
--
-- -- Sorszámok:
-- SELECT 'circuits' t, COUNT(*) FROM circuits
-- UNION ALL SELECT 'constructors',      COUNT(*) FROM constructors
-- UNION ALL SELECT 'drivers',           COUNT(*) FROM drivers
-- UNION ALL SELECT 'grandprix',         COUNT(*) FROM grandprix
-- UNION ALL SELECT 'race_result',       COUNT(*) FROM race_result
-- UNION ALL SELECT 'qualifying_result', COUNT(*) FROM qualifying_result
-- UNION ALL SELECT 'laps',              COUNT(*) FROM laps
-- UNION ALL SELECT 'stints',            COUNT(*) FROM stints;
--
-- -- RLS mindenhol bekapcsolva?
-- SELECT relname, relrowsecurity FROM pg_class
-- WHERE  relnamespace = 'public'::regnamespace AND relkind = 'r'
-- ORDER  BY relname;
--
-- -- Alkalmazott sémaverziók:
-- SELECT * FROM schema_version ORDER BY applied_at;
--
-- -- Van-e admin?
-- SELECT id, email, role FROM profiles WHERE role = 'admin';
--
-- =====================================================================